core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('user/',include('users.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.HomePageView.as_view(),name='index'),
    path('dashboard-count/',views.DashBoardCountView.as_view(),name='dashboard-count'),
    path('pending-notifications/',views.PendingTasksNotificationView.as_view(),name='pending-notifications'),
    path('clear-notifications/',views.ClearAllNotifications.as_view(),name='clear-notifications'),
    path('dashboard-task/',views.DashboardTaskView.as_view(),name='dashboard-task'),
    path('dashboard-project/',views.DashboardProjectView.as_view(),name='dashboard-project'),
    path('filter-total-projects/',views.TotalProjectFilterView.as_view(),name='filter-total-project'),
    path('filter-completed-projects/',views.CompletedProjectFilterView.as_view(),name='filter-completed-project'),
    path('filter-pending-projects/',views.PendingProjectFilterView.as_view(),name='filter-pending-project'),
    path('filter-on-hold-projects/',views.OnHoldProjectFilterView.as_view(),name='filter-on-hold-project'),
    path('filter-canceled-projects/',views.CanceledProjectFilterView.as_view(),name='filter-canceled-project'),
    path('filter-total-tasks/',views.TotalTaskFilterView.as_view(),name='filter-total-task'),
    path('filter-completed-tasks/',views.FilterCompletedTaskView.as_view(),name='filter-completed-tasks'),
    path('filter-pending-tasks/',views.FilterPendingTaskView.as_view(),name='filter-pending-tasks'),
    path('filter-inprogress-tasks/',views.FilterInProgressTaskView.as_view(),name='filter-inprogress-tasks'),
    path('filter-upcoming-tasks/',views.FilterUpcomingTaskView.as_view(),name='filter-upcoming-tasks'),
    path('activity-logs/',views.ActivityLogView.as_view(),name='activity-logs'),
    path('recent-logs-filter',views.FilterRecentActivityView.as_view(),name='recent-log-filter'),
    path('filter-dashboard-project/',views.FilterDashboardProjectView.as_view(),name='filter-dashboard-project'),
    path('filter-dashboard-task/',views.FilterDashboardTaskView.as_view(),name='filter-dashboard-task'),
    path('news-dashboard-view/',views.NewsDashboardView.as_view(),name='news-dashboard'),
    path('filter-news/',views.FilterNewsView.as_view(),name='filter-news-view'),
    path('projects/',views.ProjectPageView.as_view(),name='project-page'),
    path('project-list/',views.ProjectListView.as_view(),name='project-list'),
    path('project-detail/<int:project_id>/',views.ProjectDetailView.as_view(),name='project-detail'),
    path('create-project/',views.ProjectCreateView.as_view(),name='create-project'),
    path('add-assignee/<int:project_id>/',views.AddAssigneeView.as_view(),name='add-assignee'),
    path('project-date-range-filter/',views.ProjectDateRangeFilter.as_view(),name='project-date-range-filter'),
    path('update-project/',views.UpdateProjectView.as_view(),name='update-project'),
    path('delete-project/',views.ProjectDeleteView.as_view(),name='delete-project'),
    path('check-duplicates/',views.CheckProjectFileDuplicates.as_view(),name='check-duplicates'),
    path('upload-project/',views.ProjectFileUploadView.as_view(),name='upload-project'),
    path('project/lists/<int:project_id>/',views.ListPageView.as_view(),name='list-page'),
    path('project/lists-display/<int:project_id>/',views.ListsDisplayView.as_view(),name='list-display'),
    path('project/create-list/<int:project_id>/',views.CreateListView.as_view(),name='list-create'),
    path('update-list-view/',views.UpdateListPageView.as_view(),name='list-update-page'),
    path('update-list/',views.UpdateListView.as_view(),name='list-update'),
    path('delete-list/<int:project_id>/',views.DeleteListView.as_view(),name='delete-list'),
    path('project/lists/issues/<int:list_id>/',views.IssuePageView.as_view(),name='issue-page'),
    path('lists/issues/<int:list_id>/',views.IssueListView.as_view(),name='issue-list'),
    path('lists/create-issue/<int:list_id>/',views.IssueCreateView.as_view(),name='issue-create'),
    path('update-issue-view/',views.UpdateIssuePageView.as_view(),name='issue-update-view'),
    path('update-issue/',views.UpdateIssueView.as_view(),name='issue-update'),
    path('attach-issue-file/<int:issue_id>/',views.IssueFileAttachmentView.as_view(),name='issue-file'),
    path('remove-issue-attachment/<int:id>/',views.IssueAttachmentDeleteView.as_view(),name='issue-file-remove'),
    path('delete-issue/<int:list_id>/',views.DeleteIssueView.as_view(),name='delete-issue'),
    path('project/lists/issue-detail/<int:list_id>/',views.IssueDetailPage.as_view(),name='issue-detail'),
    path('tasks/',views.TodoPageView.as_view(),name='todo-page'),
    path('project/task-detail/<int:task_id>/',views.TaskDetailPageView.as_view(),name='task-detail'),
    path('attach-task-file/<int:task_id>/',views.TaskFileAttachmentView.as_view(),name='task-file'),
    path('tasks-list/',views.TaskListView.as_view(),name='task-list'),
    path('create-task/',views.TodoCreateView.as_view(),name='create-task'),
    path('date-range-filter/',views.DateRangeFilter.as_view(),name='date-range-filter'),
    path('update-view/',views.UpdateTaskPageView.as_view(),name='update-view'),
    path('update-task/',views.UpdateTaskView.as_view(),name='update-task'),
    path('delete-task/',views.TaskDeleteView.as_view(),name='delete-task'),
    path('task/sub-task/<int:task_id>/',views.SubTaskPageView.as_view(),name='sub-task'),
    path('task/sub-task-list/<int:task_id>/',views.SubTaskListView.as_view(),name='sub-task-list'),
    path('task/create-sub-task/<int:task_id>/',views.SubTaskCreateView.as_view(),name='sub-task-list'), 
    path('task/update-sub-task-view/<int:task_id>/',views.UpdateSubTaskPageView.as_view(),name='sub-task-update-view'), 
    path('task/update-sub-task/<int:task_id>/',views.UpdateSubTaskView.as_view(),name='sub-task-update'), 
    path('task/delete-sub-task/<int:task_id>/',views.SubTaskDeleteView.as_view(),name='sub-task-delete'), 
    path('faq/',views.FaqPageView.as_view(),name='faq'),
    path('faq-list/',views.FaqListView.as_view(),name='faq-list'),
    path('feedback/',views.FeedbackPageView.as_view(),name='feedback'),
    path('feedback-submission/',views.FeedbackCreateView.as_view(),name='feedback-submission'),
    path('all-news/',views.MainNewsPageView.as_view(),name='all-news'),
    path('news-list/',views.NewsListView.as_view(),name='news-list'),
    path('announcements/',views.AnnouncementPageView.as_view(),name='announcements'),
    path('announcements-list/',views.AnnouncementListView.as_view(),name='announcements-list'),
    path('my-news/',views.MyNewsPageView.as_view(),name='my-news'),
    path('my-news-list/',views.MyNewsListView.as_view(),name='my-news-list'),
    path('create-news/',views.CreateNewsView.as_view(),name='create-news'),
    path('news/<slug:slug>/',views.SingleNewsPage.as_view(),name='news'),
    path('announcement/<slug:slug>/',views.SingleAnnouncementPage.as_view(),name='announcement'),
    path('news-update-view/',views.NewsUpdatePageView.as_view(),name='news-update-view'),
    path('news-update/',views.NewsUpdateView.as_view(),name='news-update'),
    path('news-delete/',views.NewsDeleteView.as_view(),name='news-delete'),
    path('search-all-news/',views.AllNewsSearchView.as_view(),name='all-news-search'),
    path('announcement-search/',views.announcementSearchView.as_view(),name='announcement-search'),
    path('search-my-news/',views.MyNewsSearchView.as_view(),name='my-news-search'),
    path('all-news-filter/',views.AllNewsFilter.as_view(),name='all-news-filter'),
    path('announcement-filter-filterby/',views.AnnouncementFilterByFilter.as_view(),name='announcement-filter-filterby'),
    path('my-news-filter/',views.MyNewsFilter.as_view(),name='my-news-filter'),
    
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/',views.UserRegistrationView.as_view(),name='register'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('profile/',views.UserProfilePage.as_view(),name='profile-page'),
    path('settings/',views.UserSettingsView.as_view(),name='settings'),
    path('remove-profile-picture/',views.ProfilePictureRemoveView.as_view(),name='remove-profile'),
    path('reminder-settings/',views.ReminderSettingsView.as_view(),name='reminder-settings'),
    path('change-password/',views.ChangePasswordView.as_view(),name='change-password'),
    path('check-email/',views.CheckEmail.as_view(),name='check-email'), 
    path('check-username/',views.CheckUsername.as_view(),name='check-username')
    
]

templates/featured-news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Featured News{% endblock title %}

{% block content %}

{% include 'header.html' %}
{% include 'sidebar.html' %}

<!--main content-->
<main id="main" class="main">
  
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="search-bar mb-3">
          <form class="search-form d-flex align-items-center" method="POST" action="#" id="featuredSearchForm">
            <input class="form-control form-control-sm search" type="text" name="featuredNewsSearch" placeholder="Search latest news here" title="Enter search keyword">
            <button type="submit" class="btn btn-primary btn-sm ms-3" title="Search"><i class="bi bi-search"></i></button>
          </form>
        </div><!-- End Search Bar -->
      </div>
      <div class="col-md-6">
        <h5>Filter</h5>
        <div class="container">
          <div class="row">
              <div class="col-md-4">
                <label for="">Filter by:   </label>
                <select class="form-select dataTables_filter" name="filterBy" id="filterBy" aria-label="Default select example" >
                    <option value=''>Show all</option>
                    <option value="Today" >Today</option>
                    <option value="This Month">This Month</option>
                    <option value="This Year">This Year</option>
                </select>
              </div>
              <div class="col-md-3 mt-4">
                <button class="btn btn-primary btn-sm" id="clearFilter">Clear Filter</button>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="pagetitle ">
      <h1 class="my-3">Featured News</h1>
      <nav>
        <ul class="nav nav-tabs">

            <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:all-news' %}" >All News</a></button>
            </li>
  
            {% comment %} <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:general-news' %}" >General News</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:featured-news' %}" >Featured News</a></button>
            </li> {% endcomment %}
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:announcements' %}" >Announcements</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:my-news' %}" >My News</a></button>
            </li>
  
          </ul>
      </nav>
    </div><!-- End Page Title -->

    <div class="tab-content">
        <h3></h3>
      <section  class="section">
        <div id="newsDiv"  class="row">
          <!--news contents-->
        </div>
  
      </section>
    </div>
  </main><!-- End #main -->

{% include 'footer.html' %}

<script src="{% static 'assets/js/featured-news.js' %}"></script>
<script src="{% static 'assets/js/search-featured.js' %}"></script>
<script src="{% static 'assets/js/featured-news-filter.js' %}"></script>

{% endblock content %}

templates/footer.html
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>E8Admin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

templates/general-news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}General News{% endblock title %}

{% block content %}

{% include 'header.html' %}
{% include 'sidebar.html' %}

<!--main content-->
<main id="main" class="main">
  
  <!--Main page-->
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="search-bar mb-3">
          <form class="search-form d-flex align-items-center" method="POST" action="#" id="generalSearchForm">
            <input class="form-control form-control-sm search" type="text" name="generalNewsSearch" placeholder="Search latest news here" title="Enter search keyword">
            <button type="submit" class="btn btn-primary btn-sm ms-3" title="Search"><i class="bi bi-search"></i></button>
          </form>
        </div><!-- End Search Bar -->
      </div>
      <div class="col-md-6">
        <h5>Filter</h5>
        <div class="container">
          <div class="row">
              <div class="col-md-4">
                <label for="">Filter by:   </label>
                <select class="form-select dataTables_filter" name="filterBy" id="filterBy" aria-label="Default select example" >
                    <option value=''>Show all</option>
                    <option value="Today" >Today</option>
                    <option value="This Month">This Month</option>
                    <option value="This Year">This Year</option>
                </select>
              </div>
              <div class="col-md-3 mt-4">
                <button class="btn btn-primary btn-sm" id="clearFilter">Clear Filter</button>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="pagetitle ">
      <h1 class="my-3">General News</h1>
      <nav>
        <ul class="nav nav-tabs">

            <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:all-news' %}" >All News</a></button>
            </li>
{% comment %}   
            <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:general-news' %}" >General News</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:featured-news' %}" >Featured News</a></button>
            </li> {% endcomment %}
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:announcements' %}" >Announcements</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:my-news' %}" >My News</a></button>
            </li>
  
          </ul>
      </nav>
    </div><!-- End Page Title -->

    <div class="tab-content">
        <h3></h3>
      <section  class="section">
        <div id="newsDiv"  class="row">
          <!--news contents-->
        </div>
  
      </section>
    </div>
  </main><!-- End #main -->

{% include 'footer.html' %}

<script src="{% static 'assets/js/general-news.js' %}"></script>
<script src="{% static 'assets/js/search-general-news.js' %}"></script>
<script src="{% static 'assets/js/general-news-filter.js' %}"></script>

{% endblock content %}

templates/list-page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Lists{% endblock title %}

{% block content %}

{% include 'header.html' %}

{% include 'sidebar.html' %}

<!--todo page-->

<main id="main" class="main">

    <div class="pagetitle">
      <h1>Lists</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item active"><a href="{% url 'home:index' %}">Home</a></li>          
          <li class="breadcrumb-item"><a href="{% url 'home:project-page' %}">Projects</a></li>          
          <li class="breadcrumb-item"><a href="{% url 'home:project-detail' project.id %}">Project detail</a></li>          
          <li class="breadcrumb-item"><a class="active" href="{% url 'home:list-page' project.id %}">Lists</a></li>          
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section project-table" >
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Lists</h5>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus aliquam voluptates ipsum magnam, officiis sint maiores nesciunt quos eos, earum facilis? Voluptatem eveniet sed temporibus molestias, minus unde consequuntur quae?</p>




          
            <div class="card-body">

              <button type="button" class="btn btn-primary mb-5" data-bs-toggle="modal" data-bs-target="#listModal">
                Create List
              </button>
              <div class="modal fade" id="listModal" tabindex="-1">
                <div class="modal-dialog modal-dialog-scrollable">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Create List</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="card-body">
                        <h5 class="card-title">Create List</h5>
                        <form class="row g-3" method="post" id="listForm">
                          {% csrf_token %}
                          <div class="col-12">
                            <label for="projectTitle" class="form-label">List Name</label>
                            <input type="text" name="list_name" class="form-control" id="listName">
                          </div>
                          <div class="col-12">
                            <label for="projectDescription" class="form-label">List Description</label>
                            <textarea class="form-control" name="list_description" placeholder="Description" id="listDescription" style="height: 100px;"></textarea>
                          </div>
                          <div class="modal-footer">
                            <button type="button" id="close" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                    
              <!-- Table with stripped rows -->
              <table class="table datatable" id="listTable">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
              </table>
              <!-- End Table with stripped rows -->

    

            </div>
            <!--update modal -->
            <div class="card-body">
              <div class="modal fade" id="listUpdateModal" tabindex="-1">
                <div class="modal-dialog modal-dialog-scrollable">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Edit List</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="card-body">
                        <h5 class="card-title">Edit List</h5>
                        <form class="row g-3" method="post" id="updateListForm">
                          {% csrf_token %}
                          <div class="col-12">
                            <label for="" class="form-label">List Name</label>
                            <input type="text" name="listUpdateName" class="form-control" id="listUpdateName">
                          </div>
                          <div class="col-12">
                            <label for="projectDescription" class="form-label">List Description</label>
                            <textarea class="form-control" name="listUpdateDescription" placeholder="Description" id="listUpdateDescription" style="height: 100px;"></textarea>
                          </div>
                          <div class="modal-footer">
                            <button type="button" id="close" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>
      </div>
    </section>

    <!--Delete modal-->
    <div class="modal fade" id="deleteListModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Confirm </h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form action="" method="post" id='listDeleteForm'>
              {% csrf_token %}
              Are you sure do you want to delete this list ?
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger">Delete</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

  </main><!-- End #main -->

  {% include 'footer.html' %}

  <script src="{% static 'assets/js/lists.js' %}"></script>
  <script src="{% static 'assets/js/list-create.js' %}"></script>
  <script src="{% static 'assets/js/list-action.js' %}"></script>
  
{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}

<main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                <div class="d-flex justify-content-center py-4">
                    <a href="{% url 'home:index' %}" class="logo d-flex align-items-center w-auto">
                      <img src="{% static 'assets/img/logo.png' %}" alt="">
                      <span class="d-none d-lg-block">E8Admin</span>
                    </a>
                  </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your username & password to login</p>
                  </div>

                  <div class="login-error text-danger">
                  </div>

                  <form class="row g-3 " id="loginForm" method="post">
                    {% csrf_token %}
                    <div class="col-12">
                      <label for="yourEmail" class="form-label">Your Email</label>
                      <input autofocus type="email" name="email" class="form-control" id="yourEmail" >
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword">
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href="{% url 'users:register' %}">Create an account</a></p>
                    </div>
                  </form>

                </div>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <script src="{% static 'assets/js/validate-login.js' %}"></script>

{% endblock content %}

templates/single-announcement.html
{% extends 'base.html' %}
{% load static %}

{% block title %}My News{% endblock title %}

{% block content %}

{% include 'header.html' %}
{% include 'sidebar.html' %}

<!--main content-->
<main id="main" class="main">
  
    <div class="pagetitle ">
        <nav>
          <ul class="nav nav-tabs">
  
            <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:all-news' %}" >All News</a></button>
            </li>
  
            {% comment %} <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:general-news' %}" >General News</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:featured-news' %}" >Featured News</a></button>
            </li> {% endcomment %}
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:announcements' %}" >Announcements</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:my-news' %}" >My News</a></button>
            </li>
  
          </ul>
        </nav>
      </div><!-- End Page Title -->

    <div class="tab-content">
        <h3></h3>
      <section  class="section mt-5 ">
        <div id="singleNewsDiv"  class="row">
          <!--news contents-->
          <div class="col-lg-8">

            <div class="card">
            <div class="card-body">
                <a href=""><h5 class="card-title">{{announcement.title}}</h5></a>
                <span>published by <b>{{announcement.user.username}}</b></span><span class="text-secondary small ms-5">published on {{announcement.published_date}}&nbsp;&nbsp;{{announcement.published_time}}</span>
                <img class="newsImage mt-3" src="{{announcement.announcement_image.url}}" alt="" >
                <p class="my-5">{{announcement.description}}</p>
            </div>
            </div>
            </div>
        </div>
  
      </section>
    </div>



  </main><!-- End #main -->

{% include 'footer.html' %}

{% endblock content %}

templates/single-news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}My News{% endblock title %}

{% block content %}

{% include 'header.html' %}
{% include 'sidebar.html' %}

<!--main content-->
<main id="main" class="main">
  
    <div class="pagetitle ">
        <nav>
          <ul class="nav nav-tabs">
  
            <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:all-news' %}" >All News</a></button>
            </li>
{% comment %}   
            <li class="nav-item mx-1" role="presentation">
              <button type="button" class="nav-link active" ><a href="{% url 'home:general-news' %}" >General News</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:featured-news' %}" >Featured News</a></button>
            </li>
   {% endcomment %}
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:announcements' %}" >Announcements</a></button>
            </li>
  
            <li class="nav-item mx-1">
              <button type="button" class="nav-link active" ><a href="{% url 'home:my-news' %}" >My News</a></button>
            </li>
  
          </ul>
        </nav>
      </div><!-- End Page Title -->

    <div class="tab-content">
        <h3></h3>
      <section  class="section mt-5 ">
        <div id="singleNewsDiv"  class="row">
          <!--news contents-->
          <div class="col-lg-8">

            <div class="card">
            <div class="card-body">
                <a href=""><h5 class="card-title">{{news.title}}</h5></a>
                <span>published by <b>{{news.user.username}}</b></span><span class="text-secondary small ms-5">published on {{news.published_date}}&nbsp;&nbsp;{{news.published_time}}</span>
                <img class="newsImage mt-3" src="{{news.news_image.url}}" alt="" >
                <p class="my-5">{{news.description}}</p>
            </div>
            </div>
            </div>
        </div>
  
      </section>
    </div>



  </main><!-- End #main -->

{% include 'footer.html' %}

{% endblock content %}